name: "Prow github actions"
on:
  issue_comment:
    types: [created,edited]
  pull_request_review:
    types: [submitted,edited]
permissions:
  issues: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: carolynvs/prow-github-actions@trigger-from-review
        with:
          prow-commands: |
            /approve
            /lgtm
          github-token: "${{ secrets.GITHUB_TOKEN }}"
