name: "Prow github actions"
on:
  issue_comment:
    types: [created]
permissions:
  issues: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository so that the OWNERS file can be used by prow
      - run: hub clone ${{ github.server_url }}/${{ github.repository }} .
      - uses: carolynvs/prow-github-actions@owners-file2
        with:
          prow-commands: |
            /approve 
            /lgtm
          github-token: "${{ secrets.GITHUB_TOKEN }}"
