name: "Prow github actions"
on:
  issue_comment:
    types: [created]
permissions:
  issues: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: carolynvs/prow-github-actions@main
        with:
          prow-commands: '/approve 
            /lgtm'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
